name: c++ build with cmake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout self (hello-example)
      run: actions/checkout@v3

    - name: configure self (hello-example)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/local -CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build self (hello-example)
      run: cmake --build ${{github.workspace}}/build --verbose

    - name: test self (hello-example)
      working-directory: ${{github.workspace}}/build
      run: ./hello-example
